# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fr\FileMetadataOverlayAspect\:
    resource: '../Classes/*'

  Fr\FileMetadataOverlayAspect\Aspect\FileMetadataOverlayAspect:
    tags:
      - name: event.listener
        identifier: 'fr/file-metadata-overlay-aspect'
        method: 'frLanguageAndWorkspaceOverlay'
        event: TYPO3\CMS\Core\Resource\Event\EnrichFileMetaDataEvent
        after: 'typo3-frontend/overlay'